package sysdist;


/**
* sysdist/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sysdist.idl
* lundi, 12. novembre 2018 21.46. h WET
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
