package sysdist;


/**
* sysdist/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sysdist.idl
* lundi, 12. novembre 2018 21.46. h WET
*/

public interface HelloOperations 
{
  String sayHello ();
  void sayBye ();
} // interface HelloOperations
